SELECT COUNTRIES.CONTINENT, COUNT(*) AS NUM_IN_DECADE , ALBUMS.RELEASED AS RELEASED
CASE
    WHEN RELEASED BETWEEN 2000 AND 2010 THEN "2000's"
    WHEN RELEASED BETWEEN 1990 AND 1999 THEN "90's"
    WHEN RELEASED BETWEEN 1980 AND 1989 THEN "80's"
    WHEN RELEASED BETWEEN 1970 AND 1979 THEN "70's"
    WHEN RELEASED BETWEEN 1960 AND 1969 THEN "60's"
    WHEN RELEASED BETWEEN 1950 AND 1959 THEN "50's"
    ELSE "Oldies" END AS RANGE
  FROM ALBUMS
  JOIN ALBUM_COUNTRY
  ON ALBUMS.ALBUM_ID=ALBUM_COUNTRY.ALBUM_ID
  JOIN COUNTRIES
  ON ALBUM_COUNTRY.COUNTRY=COUNTRIES.CODE
  GROUP BY DECADES.RANGE
  ORDER BY NUM_IN_DECADE DESC;
